services:
  # app:
  #   networks:
  #     - trips
  # api:
  #   networks:
  #     - trips
  #   depends_on:
  #     - database
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_PASSWORD=master
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TRIPS
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - trips
    ports:
      - 5432:5432

networks:
  trips: