services:
  app:
    build: ./app
    container_name: app
    networks:
      - trips
    ports:
      - 80:80
  api:
    build: ./api
    container_name: api
    ports:
      - 8080:8080
    networks:
      - trips
    environment:
      - POSTGRES_PASSWORD=master
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TRIPS
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - HTTP_PORT=8080
    env_file:
      - ./.env
    depends_on:
      - database
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_PASSWORD=master
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TRIPS
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - trips
    ports:
      - 5432:5432

networks:
  trips: